export const siteConfig = {
  title: 'H3 Excavation & Construction | Central Oregon\'s Premier Excavation & Construction Company',
  description: 'Central Oregon\'s trusted excavation and construction company. Expert services in residential and commercial excavation, utility trenching, septic systems, and land development. Serving Bend, Redmond, Sisters, and all of Central Oregon.',
  keywords: () => [
    'H3 Excavation and Construction',
    'Central Oregon Excavation',
    'Bend Oregon Excavation',
    'Redmond Oregon Excavation',
    'Sisters Oregon Excavation',
    'Central Oregon Construction',
    'Bend Oregon Construction',
    'Commercial Excavation Oregon',
    'Residential Excavation Oregon',
    'Utility Trenching Oregon',
    'Septic System Installation Oregon',
    'Land Development Oregon',
    'Site Preparation Oregon',
    'Grading Services Oregon',
    'Foundation Preparation Oregon',
    'Drainage Systems Oregon',
    'Concrete Work Oregon',
    'Fencing Installation Oregon',
    'Plumbing Trenching Oregon',
    'Construction Company Bend',
    'Excavation Company Bend',
    'DEQ Certified Septic',
    'Central Oregon Contractors',
    'Bend Area Contractors',
    'Professional Excavation Services',
    'Commercial Construction Bend',
    'Residential Construction Bend',
    'Land Clearing Oregon',
    'Earthwork Services Oregon',
    'Project Management Oregon'
  ],
  url: () => 'https://www.h3excavationandconst.com',
  googleSiteVerificationId: () => process.env.GOOGLE_SITE_VERIFICATION_ID || '',
};
